# Generated by Django 2.2.7 on 2019-11-19 06:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191118_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 19, 6, 53, 59, 8790, tzinfo=utc)),
        ),
    ]
