# Generated by Django 2.2.7 on 2019-11-19 07:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191119_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 19, 7, 25, 7, 401168, tzinfo=utc)),
        ),
    ]
